project:
  type: website
  output-dir: docs

website:
  title: "Fundacja Centrum Opowiadania Świata COSik"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: docs.qmd
        text: Dokumenty

format:
  html:
    theme: cosmo